name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  Buildandpushdocker:
    runs-on: ubuntu-latest
    environment: Dev
    steps:
#       - name: docker installation 
#         run: curl -fsSL https://get.docker.com | sh 
      - name: docker login 
        run: ls 
#         run: docker login -u ${{secrets.DOCKERHUBUSERNAME}} -p ${{secrets.DOCKERHUBPASSWORD}}
#       - name: docker build 
#         run: docker build . -t fast_api:${GITHUB_SHA::7}
        
          
          
          
          
      
      

  

       

      
        

      
