name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  Buildandpushdocker:
    runs-on: ubuntu-latest
    environment: Dev
    steps:
      - name: gitclone 
        run: git clone https://github.com/Shubhambawa98/testenv.git
      - name: docker installation 
        run: curl -fsSL https://get.docker.com | sh 
      - name: docker login 
        run: docker login -u ${{secrets.DOCKERHUBUSERNAME}} -p ${{secrets.DOCKERHUBPASSWORD}}
      - name: docker build 
        run: cd testenv && docker build . -t fast_api:${GITHUB_SHA::7}
      - name: docker tag & push  
        run: docker tag fast_api:${GITHUB_SHA::7} shubhambawa98/testlkm:${GITHUB_SHA::7} && docker push shubhambawa98/testlkm:${GITHUB_SHA::7}
        
          
          
          
          
      
      

  

       

      
        

      
