name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  Buildandpushdocker:
    runs-on: ubuntu-latest
    environment: Dev
    steps:
      - name: Docker Build Tag Publish
        uses: bitovi/github-actions-docker-publish@v1.0.7
        with:
          docker_username: ${{secrets.DOCKERHUBUSERNAME}}
          docker_password: ${{secrets.DOCKERHUBPASSWORD}}
          image_tag: fast_api
          
          
          
          
      
      

  

       

      
        

      
